#!/usr/bin/env python3
"""Generate docs/design/types.md from openspec/specs/*/spec.md code blocks."""
import re, pathlib, collections
root = pathlib.Path(__file__).resolve().parent.parent
rows = collections.defaultdict(list)
dups = collections.defaultdict(list)
for p in sorted((root / 'openspec/specs').glob('*/spec.md')):
    cap = p.parent.name
    s = p.read_text()
    for block in re.findall(r'```go\n(.*?)```', s, re.S):
        illustrative = '(illustrative)' in block
        tier = 'illustrative' if illustrative else 'normative'
        for m in re.finditer(r'^type (\w+)', block, re.M):
            rows['type'].append((m.group(1), cap, tier)); dups[m.group(1)].append(cap)
        for m in re.finditer(r'^func (?:\([^)]*\) )?(\w+)', block, re.M):
            rows['func'].append((m.group(1), cap, tier))
        for m in re.finditer(r'^(?:\t|var )(Err\w+)\s*=', block, re.M):
            rows['error'].append((m.group(1), cap, tier))
        for m in re.finditer(r'^\t(\w+)\s+\w+ = (?:iota|"\w+")', block, re.M):
            rows['const'].append((m.group(1), cap, tier))
        for m in re.finditer(r'^const (\w+) ', block, re.M):
            rows['const'].append((m.group(1), cap, tier))
        for cb in re.findall(r'^const \(\n(.*?)^\)', block, re.S | re.M):
            for m in re.finditer(r'^\t(\w+)', cb, re.M):
                rows['const'].append((m.group(1), cap, tier))
HANDLES = {'Conversation', 'Flow'}
ifaces = []
for p_ in sorted((root / 'openspec/specs').glob('*/spec.md')):
    for m in re.finditer(r'^type (\w+)(?:\[[^\]]*\])? interface \{', p_.read_text(), re.M):
        ifaces.append((m.group(1), p_.parent.name, 'handle' if m.group(1) in HANDLES else 'port'))
out = ['# Types index', '', 'Generated by `tools/gen_types_index.py` from the capability specs. Every exported identifier the specs declare, with its defining capability and contract tier. Regenerate after editing any `openspec/specs/*/spec.md`; M0 task 1 diffs this against the `gohan` package.', '']
for kind, title in [('type','Types'),('func','Functions'),('const','Constants'),('error','Sentinel errors')]:
    out += [f'## {title}', '', '| Name | Capability | Tier |', '|---|---|---|']
    for name, cap, tier in sorted(set(rows[kind])):
        out.append(f'| `{name}` | `{cap}` | {tier} |')
    out.append('')
out += ['## Interfaces', '', 'Kind per `docs/design/compatibility.md`: a *port* is implemented by users or adapters and is frozen at v1 (new capability comes as an optional interface); a *handle* is implemented by gohan only and may gain methods.', '', '| Name | Capability | Kind |', '|---|---|---|']
for name, cap, kind in sorted(set(ifaces)):
    out.append(f'| `{name}` | `{cap}` | {kind} |')
out.append('')
catalog_src = (root / 'openspec/specs/messages/spec.md').read_text()
catalog_body = catalog_src[catalog_src.index('### Requirement: Error catalog'):catalog_src.index('### Requirement: Blobs')]
catalog_refs = set(re.findall(r'`\*?(Err\w+|\w+Error)\b', catalog_body))
ERR_NAME = re.compile(r'^(Err(?!or)[A-Z]\w*|[A-Z]\w{2,}Error)$')
# Every sentinel and typed error a spec declares needs a catalog row, except
# the two waivers that never reach a transport.
typed_errors = {n for n, _, _ in rows['type'] if ERR_NAME.match(n)}
waivers = {'SuspendError', 'ToolError'}
missing_rows = sorted((typed_errors | {n for n, _, _ in rows['error']}) - catalog_refs - waivers)
uncatalogued = sorted(n for n, _, _ in rows['error'] if n not in catalog_refs)
# Each table row's Source column must name something, and every Err/Error
# identifier it names must be declared by some spec.
catalog_rows = []
for line in catalog_body.splitlines():
    if not line.startswith('| `gohan.'):
        continue
    cells = [c.strip() for c in line.strip().strip('|').split('|')]
    catalog_rows.append(cells)
empty_source = sorted(cells[0] for cells in catalog_rows if len(cells) < 4 or not cells[-1])
undeclared_source = []
d = {k: v for k, v in dups.items() if len(set(v)) > 1}
defined = {n for n, _, _ in rows['type']} | {n for n, _, _ in rows['func']} | {n for n, _, _ in rows['const']} | {n for n, _, _ in rows['error']}
for cells in catalog_rows:
    if len(cells) < 4:
        continue
    for name in re.findall(r'`\*?(\w+)`', cells[-1]):
        if ERR_NAME.match(name) and name not in defined:
            undeclared_source.append((cells[0], name))
builtin = set('Second Minute Millisecond string int int64 float64 bool byte error any context time json iter io Context Seq2 RawMessage Duration Time Reader ReadCloser Writer map chan func struct interface In Out S D M'.split())
undefined = collections.defaultdict(set)
for p in sorted((root / 'openspec/specs').glob('*/spec.md')):
    cap = p.parent.name
    for block in re.findall(r'```go\n(.*?)```', p.read_text(), re.S):
        for line in block.splitlines():
            if line.lstrip().startswith('//'): continue
            body = re.sub(r'^\t\w+\s+', '\t', line) if re.match(r'^\t\w+\s+\S', line) else line
            body = re.sub(r'^\t[\w, ]+\s+(\S+)$', r'\t\1', line) if re.match(r'^\t\w+, ', line) else body
            body = re.sub(r'\b[A-Z]\w*:', '', body)
            if 'struct{' in body:
                inner = body[body.index('struct{')+7:body.rfind('}')]
                body = ' '.join(f.strip().split()[-1] for f in inner.split(';') if f.strip())
            for w in re.findall(r'\b([A-Z][A-Za-z0-9]+)\b', body):
                if w not in builtin and w not in defined and not re.match(r'^(Err|Kind|Stop|Finish|Slot|Stage|Origin|Awaiting|Entity|Verdict|Affinity|Granularity|Content|Compaction|Share|Fail|Collect|Per|Reject|Escalate|ToolChoice)', w):
                    undefined[w].add(cap)
undefined = {k: v for k, v in undefined.items() if not re.match(r'^(New|Read|Write|Put|Get|List|Load|Open|Close|Exec|Snapshot|Call|Spec|Decide|Generate|Profile|Compile|Eval|Cost|Project|Compact|Schedule|Redact|Rehydrate|Detect|Bool|String|Int|Assemble|Provide|Reserve|Complete|Append|Consume|Start|Step|Heartbeat|Suspend|Resuming|Finish|ByOperation|Stale|Reclaim|Purge|PendingInput|ByFingerprint|Invoke|Resume|Send|Name|Granularity|Version|ID|Verify|Explain|EraseSubject|Parse|Resource|Credentials|Expire|Key|Cmd|Option|Gate|Cancel|Delete|Entries|Forget|AllowUntrustedMemory|Count|Estimate|Upload|PutFeedback|Feedback|ProviderKey|Validate|Signal|Drain|Steer|Retention|Maintain|Notify|Notices|AckNotice|Health|NewHandler|Request|Handler)$', k)}
out_undef = ['## Undefined identifiers', '', ('none' if not undefined else '\n'.join(f'- `{k}`: used in {", ".join(sorted(v))}' for k, v in sorted(undefined.items()))), '']
out += ['## Duplicate definitions', '', ('none' if not d else '\n'.join(f'- `{k}`: {", ".join(sorted(set(v)))}' for k, v in sorted(d.items()))), '']
out += out_undef
# quickstart and example listings: every gohan.X must be defined
qs_missing = set()
for doc in [root / 'docs/design/scenarios.md']:
    for block in re.findall(r'```go\n(.*?)```', doc.read_text(), re.S):
        for w in re.findall(r'\bgohan\.([A-Z]\w*)', block):
            if w not in defined: qs_missing.add(w)
out += ['## Example listings', '', ('all `gohan.*` identifiers in docs/design/scenarios.md are defined' if not qs_missing else 'undefined in examples: ' + ', '.join(sorted(qs_missing))), '']
undefined.update({k: {'docs/design/scenarios.md'} for k in qs_missing})
(root / 'docs/design/types.md').write_text('\n'.join(out))
print({k: len(set(v)) for k, v in rows.items()}, 'dups:', d, 'undefined:', sorted(undefined), 'uncatalogued:', uncatalogued, 'missing-rows:', missing_rows, 'empty-source:', empty_source, 'undeclared-source:', undeclared_source)
import sys; sys.exit(1 if d or undefined or uncatalogued or missing_rows or empty_source or undeclared_source else 0)
